name: Build Modern PDF Reader

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            qt6-base-dev \
            qt6-base-dev-tools \
            libpoppler-qt6-dev \
            cmake \
            ninja-build \
            build-essential

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja

      - name: Build Project
        run: |
          cmake --build build
